FROM node:14.0.0-alpine3.10 as node

WORKDIR /usr/src/app

COPY package.json ./
COPY yarn.lock ./

RUN yarn

COPY . .

RUN yarn run ng build --prod --output-path=dist --base-href /fusionfrontend/ --deploy-url /fusionfrontend/

FROM nginx:1.13.12-alpine

COPY --from=node /usr/src/app/dist /usr/share/nginx/html

COPY ./nginx.conf /etc/nginx/conf.d/default.conf
