export enum FusionAppletBreadCrumbs {
  OVERVIEW  =   'APP.FUSION_APPLETS.BREAD_CRUMBS.OVERVIEW',
  ARCHIVE  =   'APP.FUSION_APPLETS.BREAD_CRUMBS.ARCHIVE',
  APPLET_DETAIL  =   'APP.FUSION_APPLETS.BREAD_CRUMBS.APPLET_DETAIL',
  APPLET_EDITOR  =   'APP.FUSION_APPLETS.BREAD_CRUMBS.APPLET_EDITOR',
}
