export enum FactoryManagerPageType {
  FACTORY_SITE_LIST,
  FACTORY_SITE_DETAIL,
  ASSET_LIST,
  ASSET_DETAIL,
  ROOM_LIST,
  ROOM_DETAIL,
  ASSET_CARD,
}

export enum FactoryManagerBreadCrumbs {
  FACTORY_SITES = 'APP.FACTORY.BREAD_CRUMBS.FACTORY_SITES',
  ASSET_CARDS = 'APP.FACTORY.BREAD_CRUMBS.ASSET_CARDS',
  ROOMS = 'APP.FACTORY.BREAD_CRUMBS.ROOMS',
  ASSETS = 'APP.FACTORY.BREAD_CRUMBS.ASSETS',
  PERFORMANCE = 'APP.FACTORY.BREAD_CRUMBS.PERFORMANCE',
  ACTIVE_APPLETS = 'APP.FACTORY.BREAD_CRUMBS.ACTIVE_APPLETS',
  ARCHIVED_APPLETS = 'APP.FACTORY.BREAD_CRUMBS.ARCHIVED_APPLETS',
  DIGITAL_NAMEPLATE = 'APP.FACTORY.BREAD_CRUMBS.DIGITAL_NAMEPLATE',
  SUBSYSTEMS = 'APP.FACTORY.BREAD_CRUMBS.SUBSYSTEMS',
  NOTIFICATIONS = 'APP.FACTORY.BREAD_CRUMBS.NOTIFICATIONS'
}

export class RouteData {
  public pageTypes: FactoryManagerPageType[];
}
