
export enum NotificationsBreadCrumbs {
  CLEARED_NOTIFICATION  =   'APP.NOTIFICATIONS.BREAD_CRUMBS.CLEARED_NOTIFICATION',
  OPEN_NOTIFICATION  =   'APP.NOTIFICATIONS.BREAD_CRUMBS.OPEN_NOTIFICATION',
}
