
export enum EcosystemBreadCrumbs {
   ASSET_TYPES = 'APP.ECOSYSTEM.BREAD_CRUMBS.ASSET_TYPES',
   ASSET_TYPE_TEMPLATES = 'APP.ECOSYSTEM.BREAD_CRUMBS.ASSET_TYPE_TEMPLATES',
   METRICS_AND_ATTRIBUTES =  'APP.ECOSYSTEM.BREAD_CRUMBS.METRICS_AND_ATTRIBUTES',
   QUANTITY_TYPES =  'APP.ECOSYSTEM.BREAD_CRUMBS.QUANTITY_TYPES',
   UNITS = 'APP.ECOSYSTEM.BREAD_CRUMBS.UNITS'
}
